# Generated by Django 4.1 on 2022-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
