# Generated by Django 4.1 on 2022-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='release_date',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
